### ISSUE TITLE
PYPI ve Python paketi

### ISSUE THREAD

**Issue by kurth4cker** [bc1428/KaninBC_War#2]
bunu pip için kurulabilir hale getirmeye çalışalım mı? bizim için bir deneyim olur. ben yeni yeni python paketleme öğrenmeye başladım da bunu deneyecek yer arıyorum :)

**Comment by bc1428** [comment]
Tamam dost sen kafana göre takıl bana bildirirsin. Ben pek bakamam ama arasıra bir göz gezdiririm. Sana kolay gele
